# config file for automatic testing at travis-ci.org
language: python

python:
	- "3.4"
	- "3.3"
	- "2.7"
	- "pypy"

install:
	- pip install -r requirements.txt
	- pip install --editable .
	- pip install coveralls

script:
	# command to run tests and collect test coverage
	- coverage run --source flask_obfuscateids setup.py test

after_success: coveralls